dist: trusty
addons:
  chrome: stable

language: node_js

node_js:
  - 6
  - 7
  - 8

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_install:
  - npm install -g grunt-cli
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - npm prune && npm install
  - node_modules/protractor/bin/webdriver-manager update
  - node_modules/protractor/bin/webdriver-manager start 2>&1 &
  - sleep 3

script:
  - grunt test

cache:
  directories:
    - node_modules
